spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jobs_saved?useSSL=false&serverTimezone=UTC
    username: root
    password: Guk726jAb*
  jpa:
    hibernate:
      ddl-auto: update   # automatically creates tables from your entities
    show-sql: true       # prints SQL queries in console
    database-platform: org.hibernate.dialect.MySQLDialect


